spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms_db?useSSL=false&characterEncoding=utf8
    username: root
    password: qq09128418..
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.xiaohei.wms.server.dao
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8082
